"""Create vehicle model

Revision ID: v1.0.02
Revises: v1.0.01
Create Date: 2025-01-04 13:43:34.005778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v1.0.02'
down_revision = 'v1.0.01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('model', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('initial_mileage', sa.Integer(), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=True),
    sa.Column('registration_expiry_date', sa.Date(), nullable=True),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
